### ISSUE TITLE
Change size of node

### ISSUE THREAD

**Issue by nikil07** [Team-Blox/TreeView#10]
Hi,
Thanks a lot for the wonderful library. Great work on it.
Just had a query, and I didn't know where else to ask. 

Is it possible to change the size of a node? XML or programatically?
Changing the node layout's size parameters didn't seem to help.

Thanks, 
Nikhil

**Comment by DennisBlock** [comment]
Hi nikil07,

thanks for your feedback. We appreciate it.

It should work now via XML.

**Comment by nikil07** [comment]
Hi,
I do not understand.
Can I change the size of node now? Please advice how to.

I do not see any changes to xml parameters to set size of node.

Thanks
Nikhil

**Comment by DennisBlock** [comment]
Just change your layout_width and layout_height attributes in your node.xml like this:
```
<LinearLayout
        android:layout_width="100dp"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <TextView
            android:id="@+id/textView"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textColor="@android:color/white"
            android:textStyle="bold"/>

</LinearLayout>
```

Or did you mean something else?

**Comment by nikil07** [comment]
Haa, cool cool. 
sorry I missed that. 

Thank for the quick fix. :)
