### ISSUE TITLE
Make TreeAdapter Public

### ISSUE THREAD

**Issue by commonsguy** [Team-Blox/TreeView#11]
Right now, `TreeAdapter` is package-private. That seems to cause problems for Kotlin.

If I have a `TreeView` named `tree`, and I try `tree.adapter = MySubclassofBaseTreeAdapter()`, I get a warning:

```
Type TreeAdapter<(raw) Any!>! is inaccessible in this context due to: public/*package*/ interface TreeAdapter<VH : Any!> : Adapter, TreeNodeObserver defined in de.blox.treeview in file TreeAdapter.class
```

If I use `tree.setAdapter(MySubclassofBaseTreeAdapter())`, it compiles, but I crash at runtime:

```
java.lang.IllegalAccessError: Illegal class access: 'com.commonsware.android.MyTreeFragment' attempting to access 'de.blox.treeview.TreeAdapter' (declaration of 'com.commonsware.android.MyTreeFragment' appears in ...)
```

Basically, the method signature of `setAdapter()` refers to a type (`TreeAdapter`) that is inaccessible to us. Apparently, plain Java can get past this, but Kotlin appears to not like it. IMHO, it's also strange to have a public method relying on a non-public type.

If possible, please make `TreeAdapter` public.

Thanks for considering this!

**Comment by DennisBlock** [comment]
Hi,

thanks for your suggestion. It makes sense, its public now.

**Comment by commonsguy** [comment]
I can confirm that this clears up the Kotlin problem &mdash; many thanks!

**Comment by GregorBlock** [comment]
I don't know if you already noticed version 0.1.2 has a bug. You should better update to the current version 0.1.3!
