### ISSUE TITLE
Strange Situation 

### ISSUE THREAD

**Issue by Brainnovo** [Team-Blox/TreeView#12]
I have this strange issue and I cannot figure out if it is a problem in my code or in your library: Please have a look at this question on stackoverflow:  https://stackoverflow.com/questions/51497307/strange-situation-while-working-with-team-blox-treeview. Note: I'm sorry if this is not properly formatted, but I have an outdated version of windows 10 and text style options are not working. Than you.

**Comment by DennisBlock** [comment]
Hi,

thanks for letting us know. The update to 0.1.1 caused some issues, but it should work now like before. Please try it with the new 0.1.3 Version.

**Comment by Brainnovo** [comment]
The problem is fixed. Thank you.
