### ISSUE TITLE
horizontal tree support? 

### ISSUE THREAD

**Issue by herald25santos** [Team-Blox/TreeView#14]
Is it possible to start from the left side(parent) to the right side(nodes)? if possible kindly help me to modify the codes or tell me what should I do to aim horizontal tree. Thanks in advance it will really helps.

**Comment by herald25santos** [comment]
is it possible to start from the left side(parent) to the right side(nodes)?

**Comment by DennisBlock** [comment]
We added orientation support in the new version. All you have to do is using the `BuchheimWalkerConfiguration.Builder.setOrientation(int)` with either `BuchheimWalkerConfiguration.ORIENTATION_LEFT_RIGHT` or `BuchheimWalkerConfiguration.ORIENTATION_RIGHT_LEFT`

This version has a breaking change, so you need to adapt to the new data structure.

**Comment by herald25santos** [comment]
You are a miracle sir that is nice to hear. It really helps to me sir God bless. Sir I have also one question about the lines of the nodes can I modify it? I want to change it to arrow line instead of line? thanks.

**Comment by GregorBlock** [comment]
thank you for your feedback. We will implement this next time.

**Comment by yudikarma** [comment]
hi @GregorBlock  are this feature already support in this version  ? thanks anyway for awesome third-party library :+1:

**Comment by yudikarma** [comment]
sorry i mean. that child to bootom and Right. like sidebar Strcuture Folder project in android studio.

**Comment by GregorBlock** [comment]
@yudikarma this kind of feature is not supported yet. Please create a feature request and describe your problem in detail.
