### ISSUE TITLE
Draw single node

### ISSUE THREAD

**Issue by ntngocanh21** [Team-Blox/TreeView#16]
Could you tell me how to draw a node which doesn't have the parent node?

**Comment by GregorBlock** [comment]
What do you mean exactly? A single node next to a graph, because that doesn't work with the current algorithms.

**Comment by ntngocanh21** [comment]
Sorry, it's my mistake. I mean the node doesn't have any child. I just want to have only one node on the graph.

**Comment by GregorBlock** [comment]
oh i see it's not possible, we change the api in the next release. Thanks

**Comment by ntngocanh21** [comment]
Thank you!

**Comment by DennisBlock** [comment]
We added two new methods for this: addNode(Node) and addNodes(Node...).
