### ISSUE TITLE
Why this graphview dont have add child

### ISSUE THREAD

**Issue by williamwong9090** [Team-Blox/TreeView#17]
May i know why this treeview library dont had contain addchild and setRootNode function ?

**Comment by GregorBlock** [comment]
Duplicate of #16

**Comment by GregorBlock** [comment]
This library is in an early stage of development. The method addNode(Node...) will be added in the next release.

**Comment by williamwong9090** [comment]
Hi Sir


Sorry for disturbing . May i know when you will release update on Graph View ?


Thank



Cc: williamwong9090; Author
Subject: Re: [Team-Blox/GraphView] Why this graphview dont have add child (#17)


This library is in an early stage of development. The method addChild(Node) will be added in the next release.

**Comment by GregorBlock** [comment]
as we are still working on the zoom feature, probably during the week.
