### ISSUE TITLE
Wrong position when clicking，Is it related to the Zoomlayout inheritance？

### ISSUE THREAD

**Issue by jackerjin** [Team-Blox/TreeView#18]

**Comment by DennisBlock** [comment]
Yes, it is because of ZoomLayout. If you have any clickable views inside your node or even using the Adapter.OnItemClickListener, you have to set hasClickableChildren to true.

As you have mentioned this, I took a look in our sample and it's missing there too. I'm adding it now.

**Comment by jackerjin** [comment]
Yes, thank u.
