### ISSUE TITLE
Delete the node what has a child node.

### ISSUE THREAD

**Issue by ntngocanh21** [Team-Blox/TreeView#19]
Hi. I got a problem when deleting a node in the Graph. It works with the node doesn't have any child node, but when I delete the node has some child node below it, I received the error message :
"java.lang.NullPointerException: Attempt to invoke virtual method 'int de.blox.graphview.tree.BuchheimWalkerNodeData.getDepth()' on a null object reference"
How can I resolve it?

**Comment by DennisBlock** [comment]
This should be fixed in 090b25627bc4be62013b5999e223eb2de59ed01b. Please use the new `0.4.1` version.

**Comment by thuijssoon** [comment]
Where can I find the new version? I am not seeing any new releases or tags...

**Comment by DennisBlock** [comment]
You were right, I forgot to add a release on Github and created one right one. Besides that, all new versions are uploaded to JCenter, so just change the version number in the gradle file and you're ready to go.

**Comment by ntngocanh21** [comment]
Thank you very much. Your team worked very well.

And I had another problem, the graph can change zoom level when I delete a node but it didn't work when I add a new node. I have to zoom out to see all nodes of the graph after that.

**Comment by thuijssoon** [comment]
> You were right, I forgot to add a release on Github and created one right one. Besides that, all new versions are uploaded to JCenter, so just change the version number in the gradle file and you're ready to go.

Great, thanks so much for your work!

**Comment by DennisBlock** [comment]
@ntngocanh21 This seems to be a "problem" with ZoomLayout. We'll see what we can do.

**Comment by karankharecha** [comment]
> @ntngocanh21 This seems to be a "problem" with ZoomLayout. We'll see what we can do.

did you find any solution for this issue?
