### ISSUE TITLE
Zoom level changes based on the size of the graph

### ISSUE THREAD

**Issue by thuijssoon** [Team-Blox/TreeView#20]
I really like this project, thanks for making it available on GitHub!

It appears that the zoom level changes based on the size of the graph, is this intentional?

**Comment by DennisBlock** [comment]
Thanks! We're glad you like it.

Yes, it is a default value from ZoomLayout. If you want to disable this, just use `app:transformation="none"` or the `setTransformation()` Method.

Altough the transformation should be only applied once, in our use case the content dimensions change everytime the graph is calculated (after adding/removing a node) and the transformation is re-applied. 

Maybe it is a bit confusing, when the zoom level changes automatically every time.

**Comment by thuijssoon** [comment]
That did the job, thanks!
