### ISSUE TITLE
Adapter delegate pattern

### ISSUE THREAD

**Issue by thuijssoon** [Team-Blox/TreeView#21]
Not so much an issue as a question... 

Have you considered using the '[adapter delegate](http://hannesdorfmann.com/android/adapter-delegates)' pattern? It could enhance flexibility and could keep the adapter cleaner. I have used a project called [Groupie](https://github.com/lisawray/groupie) in the past that I have found very useful in separating my presentation code from the domain model.

**Comment by DennisBlock** [comment]
That's a great idea, we will implement it.

**Comment by NadeemRawther** [comment]
how can i add two or three text data on this node and how can i make it dynamically create node and make edges according to the data coming from server

**Comment by GregorBlock** [comment]
I think we should not favour any particular pattern. In the end, everyone should decide for themselves how the library should be integrated into the codebase. If you have further input on this, don't hesitate to reopen this issue or post a new one.
