### ISSUE TITLE
Zoom doesn't change after new node added

### ISSUE THREAD

**Issue by DennisBlock** [Team-Blox/TreeView#22]
And I had another problem, the graph can change zoom level when I delete a node but it didn't work when I add a new node. I have to zoom out to see all nodes of the graph after that.

_Originally posted by @ntngocanh21 in https://github.com/Team-Blox/GraphView/issues/19#issuecomment-434919271_

**Comment by GregorBlock** [comment]
Closed. Zoomengine is not longer part of grapview.
