### ISSUE TITLE
onItemClickListener position issue

### ISSUE THREAD

**Issue by perusudroid** [Team-Blox/TreeView#23]
When the tree view is zoomed in adapter's onItemClickLisener picks the lastly selected position item instead of the new position. Also when the tree view is zoom out onItemClickListener not even triggering. It's really an awesome library.. it would be much better if it is has improved onClick listener/ onItemClick Listener.

**Comment by DennisBlock** [comment]
Did you use `app:hasClickableChildren="true"`? It's necessary if you want to use the `OnItemClickListener`. This is because of the ZoomLayout we're using for the zoom.  There is a link in the readme to it for further explanations.

**Comment by perusudroid** [comment]
That's great!. Work perfect.. thanks for your comment.
