### ISSUE TITLE
Tree Center issue

### ISSUE THREAD

**Issue by sagar24v** [Team-Blox/TreeView#24]
I am not able to display tree in center of view,  also not able to scroll in center
![device-2018-12-04-144344](https://user-images.githubusercontent.com/31433205/49431299-2d999480-f7d3-11e8-864e-3daa58464151.png)

**Comment by thuijssoon** [comment]
Hi @sagar24v,

It's impossible to provide help without seeing any code. Could you maybe post some of the layout files that you use?

**Comment by yagneshb** [comment]
[1912409171.pdf](https://github.com/Team-Blox/GraphView/files/2648447/1912409171.pdf)

Here is the xml code of the activity, please check it.
The tree should be with in the white box in the screenshot described above, but by default it fits in the whole screen view, rather than in bounded view.

> Hi @sagar24v,
> 
> It's impossible to provide help without seeing any code. Could you maybe post some of the layout files that you use?

**Comment by sagar24v** [comment]
> [1912409171.pdf](https://github.com/Team-Blox/GraphView/files/2648447/1912409171.pdf)
> 
> Here is the xml code of the activity, please check it.
> The tree should be with in the white box in the screenshot described above, but by default it fits in the whole screen view, rather than in bounded view.
> 
> > Hi @sagar24v,
> > It's impossible to provide help without seeing any code. Could you maybe post some of the layout files that you use?

Any update?, how can i fix this issue

**Comment by DennisBlock** [comment]
I just tested it with your layout and it works just fine. Which version of GraphView do you use?

**Comment by sagar24v** [comment]
0.4.2

**Comment by DennisBlock** [comment]
Can you upload a complete working sample with this issue? I tried a few changes, but everything works as expected, so it's easier to for us to check.

**Comment by sagar24v** [comment]
> Can you upload a complete working sample with this issue? I tried a few changes, but everything works as expected, so it's easier to for us to check.

I Am using graphview in fragment, so i attach this fragment class can you check it and update me
TreeFragment : http://dpaste.com/0J5B0ET

**Comment by sagar24v** [comment]
> > Can you upload a complete working sample with this issue? I tried a few changes, but everything works as expected, so it's easier to for us to check.
> 
> I Am using graphview in fragment, so i attach this fragment class can you check it and update me
> TreeFragment : http://dpaste.com/0J5B0ET

Hello Bro any Update? i need to solve this issue today on may app

**Comment by GregorBlock** [comment]
Your code snipped seems okay, but we can't execute it to test it out and replicate the issue. We need a fully functional minimal working sample with the issue so we can try to fix it. Just delete everything (in a new project) that doesn't need to be there for displaying the misplaced tree. A repository here on GitHub would be perfect. You can delete it afterwards.

**Comment by sagar24v** [comment]
My code working fine with Android Oreo API level 27 but not working in below version can you check it. attach screenshot from oreo
![image](https://user-images.githubusercontent.com/31433205/49647923-0bf61280-fa4a-11e8-83dd-f6913e0cc522.png)
i also add my sample code pls check in all device : 
[Fdemo.zip](https://github.com/Team-Blox/GraphView/files/2657374/Fdemo.zip)

**Comment by DennisBlock** [comment]
Yes, it seems to be a problem with different OS versions/API levels, but it's not an issue with GraphView but with ZoomLayout (the underlying zoom engine). I found an issue with the same problem [here](https://github.com/natario1/ZoomLayout/issues/32) and [here](https://github.com/natario1/ZoomLayout/issues/22).

**Comment by sagar24v** [comment]
So How i Solve this issue? it is possible to remove zoom feature from graphview?

**Comment by sagar24v** [comment]
> So How i Solve this issue? it is possible to remove zoom feature from graphview?

is it possible to fix this issue?

**Comment by sagar24v** [comment]
Any Update?

**Comment by DennisBlock** [comment]
I found the issue and created a [PR](https://github.com/natario1/ZoomLayout/pull/62) in ZoomLayout. This should fix it. I can't say when it will be merged so I found a simple workaround for you in the meantime. 

```
public class WorkaroundGraphView extends GraphView {
    int[] viewLocation = new int[2];

    public WorkaroundGraphView(Context context) {
        super(context);
    }

    public WorkaroundGraphView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public WorkaroundGraphView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    @Override
    public void onUpdate(ZoomEngine helper, Matrix matrix) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.N && getChildCount() > 0) {
            final View childAt = getChildAt(0);
            childAt.getLocationInWindow(viewLocation);
            matrix.postTranslate(viewLocation[0], viewLocation[1]);
        }
        super.onUpdate(helper, matrix);
    }
}
```
Just use this class instead of the normal GraphView until the fix is merged.

**Comment by sagar24v** [comment]
Thanks brother issue is fix now,

**Comment by sagar24v** [comment]
Thanks brother issue is Fix Now
