### ISSUE TITLE
click on node is not working

### ISSUE THREAD

**Issue by kunjanrshah** [Team-Blox/TreeView#25]
I want to click on particular node and navigate to another screen. But when i click on particular node it is not working.
- click worked in some else in the screen instead of particular node.

**Comment by GregorBlock** [comment]
Maybe this can help you #23

**Comment by kunjanrshah** [comment]
Thanks bro, you save my life.

**Comment by GregorBlock** [comment]
You're Welcome, in the next release, we should set has Clickable Children to true by default.
