### ISSUE TITLE
When zoom in/out tree is gone

### ISSUE THREAD

**Issue by sagar24v** [Team-Blox/TreeView#27]
please see in below video when  i zoom in/out on landscape mode some time tree is gone and again display

https://www.dropbox.com/s/1a6d3lpem05n7qy/device-2018-12-14-151341.mp4?dl=0

**Comment by DennisBlock** [comment]
It seems to be caused by the workaround provided earlier. Please try it again with the new version of ZoomLayout (1.4.0). You can force the new version to overwrite the one used from GraphView.

```    
implementation('de.blox:graphview:0.4.2')
{
   exclude group: "com.android.support"
   exclude group: "com.otaliastudios"
}
implementation('com.otaliastudios:zoomlayout:1.4.0') {
   force = true
}
```

**Comment by sagar24v** [comment]
okk thanks
