### ISSUE TITLE
Does minSdkVersion really need to be 16?

### ISSUE THREAD

**Issue by renyuneyun** [Team-Blox/TreeView#35]
It's really nice to see this library. I'm wondering for such a library for a long time.

For my case, there is a problem because [my app](https://github.com/renyuneyun/Easer/) has minSdkVersion 15 while this library is 16.
So... Is it really necessary for GraphView to have minSdkVersion set to 16? I thought most SDK updates are not related to what this library is supposed to provide, so this is not necessary.

**Comment by GregorBlock** [comment]
unfortunately yes, because of the underlying zoom library!

**Comment by renyuneyun** [comment]
Whoops, that's really unfortunate...

But anyway, this library is my best bet. Thank you for the work!

Shall this be issue be closed, or wait in case the zoom library would consider supporting API 15?

**Comment by GregorBlock** [comment]
thanks, since zoomlayout will probably not support API level 15 or below, I close the issue.
