### ISSUE TITLE
How can I get item layout from adapter ?

### ISSUE THREAD

**Issue by jemmycalak** [Team-Blox/TreeView#46]
I was try with this script but nothing happen.

View v =adapter.getView(0, null, graphView);
TextView t = v.findViewById(R.id.t1);
t.setText("TEST");

**Comment by DennisBlock** [comment]
You're using this library in the wrong way. GraphView works similar to how you would use the RecyclerView. Create the adapter with the viewholder pattern. In the viewholder you have your item view, where you get your child views from. If you look in the readme you find an example or look in the sample folder.

**Comment by jemmycalak** [comment]
yes, I was do same like you say, my graph is showing,, but I want to custom the node by get item layout from adapter..

Can you show me the simple code to that case ?  I was see the sample code but nothing

**Comment by DennisBlock** [comment]
What do you mean by "custom the node"? If you just want to change your data, you have to change it in the node object inside the graph. Then just call `adapter.notifyInvalidated()` to update the view.

Setting the data to the views should only be done inside the adapters `onBindViewHolder` method.

**Comment by jemmycalak** [comment]
custom node layout,, not data of node. 

I want to change item layout with different way,, not on onBindView,,
Can I do that ?

**Comment by DennisBlock** [comment]
You can change the item layout in the `onCreateViewHolder` method, like here:
https://github.com/Team-Blox/GraphView/blob/43dd72340ce08dba9f62cb0c5228a2d56206414c/sample/src/main/java/de/blox/graphview/sample/GraphActivity.java#L47

Create a layout xml for your item and inflate it in this method. For different layouts in one graph you have to implement the getItemViewType and check the view type in `onCreateViewHoler`. 

Like I said earlier, GraphView can be used just like a RecyclerView. You can google your problem and adapt the solution to GraphView or ask on StackOverflow.

**Comment by jemmycalak** [comment]
yes,, that is still in onCreateView method, I want to different way, outside OnCreateView. like this: 

https://stackoverflow.com/a/54751851

can I do that ?
thank you for your support.

**Comment by DennisBlock** [comment]
No, this is not possible.
