### ISSUE TITLE
if  view only has two onde or one node the node will dispay so big  it is so ugly how cani  change it  

### ISSUE THREAD

**Issue by mybirthfather** [Team-Blox/TreeView#50]
if  view only has two onde or one node the node will dispay so big  it is so ugly how cani  change it

**Comment by GregorBlock** [comment]
Since it is a zoom issue, check out the transformation section of the zoomlayout lib doku.

**Comment by mybirthfather** [comment]
> Since it is a zoom issue, check out the transformation section of the zoomlayout lib doku.

thank you i will try

**Comment by mybirthfather** [comment]
> section

thank you  so much  i add         app:transformation="none"  now  it loos  beauty now
