### ISSUE TITLE
Is TreeView the same GraphView, Similar IOS library

### ISSUE THREAD

**Issue by SaeedZhiany** [Team-Blox/TreeView#55]
Hi,

Thanks for this great library. I know it might not the right place to ask these questions so I hope to forgive me.

1. on the internet there are some tutorials and web pages (like [this one](http://www.digitalmirko.com/androidTreeViewLibraryDemoApp.html)) that use a library named `treeview`, but when I click on those links I head to this library, was there a renaming on this repository and `treeview` is the same as `Graphview`?

2. Is there a similar library (with similar features) for IOS platform? (I couldn't find any after one-hour searching) I want to create a react-native library that wraps this library and gives similar functionalities on React-Native side and I need to find a native IOS library for supporting both Android and IOS platforms.

**Comment by GregorBlock** [comment]
Hi @SaeedZhiany, yes it's the same library. At the beginning we had only implemented the tree layout. Over time more layouts were added and we renamed the repository from TreeView to Graphview. Unfortunately I don't know if there is a similar project for iOS. Maybe someone knows a bit more in Stackoverflow. Good luck

**Comment by SaeedZhiany** [comment]
Thanks for your response, Yeah but questions like "is there any library that do ... " are not allowed in Stackoverflow, so I asked it here. it seems I should search more. :)))

**Comment by robbysmeticapps** [comment]
@SaeedZhiany Did you find a iOS library for this ?

**Comment by SaeedZhiany** [comment]
Hello @robbysmeticapps, No I developed a pure js solution myself and used it for my react-native application.
