### ISSUE TITLE
Connect lines are not display with high sibling separation

### ISSUE THREAD

**Issue by nico6122** [Team-Blox/TreeView#56]
I have to recreate a big tree diagram, this have a lot nodes ( around 100) and there have a big separation next to the other and with this, the lines are not drawing.

If you want to simulate the problem, set (can be use the same initial example of the github):

.setSiblingSeparation(10000)

and you will see the problem.

**Comment by GregorBlock** [comment]
Hi @nico6122 , I tried it on our sample and couldn't reproduce it. I tested it with the AVD emulator (API level 28) and the current library version. Maybe your graph is too big to see the edges, have you tried zooming in?

**Comment by nico6122** [comment]
thx for the answer, i tried to zoom in but the nodes with large separation are not draw the lines, this phone is api 24.
I tried with another phone with api 28 and all the lines are drawing.

mmmm the problem is there , but i can avoid it  xd.

**Comment by GregorBlock** [comment]
hhmm okay, give me some time to check it out.

**Comment by GregorBlock** [comment]
I couldn't reproduce it with the emulator and API level 24. I would suggest you try to execute your code with the emulator as well, if it works then it musst be probably a device side issue.

**Comment by nico6122** [comment]
I tried it with the api 24 emulator and all the lines are drawn, it must be my phone as you say.

Thanks anyway, I will use my other phone with a higher api.
