### ISSUE TITLE
How Resize when changed graph?

### ISSUE THREAD

**Issue by nico6122** [Team-Blox/TreeView#58]
if i have 2 diferent graph (medium size):
 
 - graph1;
 - graph2;

and i start loading the first

 - adapter.setGraph(graph1);

and then, i change for the other:

- adapter.setGraph(graph2);

i would like to zoomout and center with the size of graph2. Its is possible?

**Comment by DennisBlock** [comment]
Since GraphView inherits from [ZoomLayout](https://github.com/natario1/ZoomLayout) you can use  `zoomTo(zoom, animate)`, when changing the graph. Look at the documentation for ZoomLayout for other methods.

**Comment by nico6122** [comment]
i knew that function, the problem is that i need to move and zoom the graph2 on change. Something like a listener that trigger after graph render and then set the new zoom and pan.

i tried with ZoomEngine listener (@Override onUpdate), but is too generic i need something more specific.
