### ISSUE TITLE
Why last row not rendering in Sugiyama Algorithm?

### ISSUE THREAD

**Issue by yoloroy** [Team-Blox/TreeView#63]
`
add.setOnClickListener{
            if (clicked_nodes.size == 1) {
                graphView.adapter.graph.addEdge(Node(clicked_nodes[0]), Node(nodeCount))
                graphView.adapter.notifyInvalidated()

                nodesData.add(0)
                nodeCount++
            } else {
                try {
                    graphView.adapter.graph.addEdge(searchNodeByData(0, graphView.adapter.graph.nodes), Node(nodeCount))
                } catch (e: ArrayIndexOutOfBoundsException) {
                    graphView.adapter.graph.addEdge(Node(0), Node(nodeCount))
                }
                graphView.adapter.notifyInvalidated()

                nodesData.add(0)
                nodeCount++
            }
        }
`

![2020-02-11_00-38-09](https://user-images.githubusercontent.com/33396665/74192609-e6c0ed80-4c66-11ea-93c3-e96aa630227b.png)

**Comment by yoloroy** [comment]
After debug, I found out that other Nodes fully not exists as Views

**Comment by yoloroy** [comment]
![2020-02-11_21-13-48](https://user-images.githubusercontent.com/33396665/74265350-758b4400-4d13-11ea-980d-5ffdb2de1e5e.png)

**Comment by DennisBlock** [comment]
Thats odd. Could you create a repo with a small executable sample project which shows this issue, so we can look at it?

**Comment by yoloroy** [comment]
I created new project and copy my code, then problem solves... o_0


![2020-02-12_20-47-43](https://user-images.githubusercontent.com/33396665/74362155-3c1d0c00-4dd9-11ea-949f-d8efe1b72f6f.png)

**Comment by yoloroy** [comment]
Problem solves, in original project I added bottom padding and this breaks last row, hah

**Comment by GregorBlock** [comment]
Yes we should include the padding in the view calculation. Thanks for that.

**Comment by GregorBlock** [comment]
This should be fixed in the new version! Try v0.7.0
