### ISSUE TITLE
BuchheimWalker Lines merged into one

### ISSUE THREAD

**Issue by AndreuZaitsev** [Team-Blox/TreeView#67]
Is it possible to separate lines? They are merged into one 
<img width="314" alt="Screen Shot 2020-03-20 at 22 00 03" src="https://user-images.githubusercontent.com/32218232/77197569-7bd0c500-6af6-11ea-9f1a-2d067855a437.png">

**Comment by GregorBlock** [comment]
Therefore you have to create a new `EdgeRenderer` and pass it with `Algorithm.setEdgeRenderer(EdgeRenderer)`

**Comment by GregorBlock** [comment]
What does your graph structure look like? I noticed that the childs have several parents, this is not supported by BuchheimWalker. We already have a TODO for this which defines the appropriate checks.

**Comment by AndreuZaitsev** [comment]
@GregorBlock I've used BuchheimWalker for this. This type of algorithm doesn't support cyclic, throws memory error, but many-to-many is ok for this. 
P.S. I've found the solution to my question. I just modify a renderer a little bit.
