### ISSUE TITLE
Not able to display the TreeView

### ISSUE THREAD

**Issue by NONOLGG** [Team-Blox/TreeView#7]
The tree view is not displaying. Below is my code. 
I actually use it in a coordinatorLayout associated with a fragment. 
Bellow is my code to initiate the TreeView. 
`@Override

    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_my_with_tree_view, container, false);
        ...
		initTreeView(view);
	}
    TreeView customTreeView;
    private void initTreeView(View view) {
    customTreeView = view.findViewById(R.id.treeView);
	BaseTreeAdapter adapter = new BaseTreeAdapter<ViewHolder>(mainActivity, R.layout.tree_view_node) {
            @NonNull
            @Override
            public ViewHolder onCreateViewHolder(View view) {
                return new ViewHolder(view);
            }
            @Override
            public void onBindViewHolder(ViewHolder viewHolder, Object data, int position) {
                viewHolder.mTextView.setText(data.toString());
                //viewHolder.mTextViewDetails.setText(data.toString());
            }
        };
        customTreeView.setAdapter(adapter);

        // example tree
        rootNode = new TreeNode(getNodeText());
        rootNode.addChild(new TreeNode(getNodeText()));
        final TreeNode child3 = new TreeNode(getNodeText());
        child3.addChild(new TreeNode(getNodeText()));
        final TreeNode child6 = new TreeNode(getNodeText());
        child6.addChild(new TreeNode(getNodeText()));
        child6.addChild(new TreeNode(getNodeText()));
        child3.addChild(child6);
        rootNode.addChild(child3);
        adapter.setRootNode(rootNode);
    }
    private int nodeCount = 0;
    private String getNodeText() {
        return "Referee " + nodeCount++;
    }`
Please can anyone tell me what is missing ?

**Comment by GregorBlock** [comment]
Hi we tested it with Fragment and ConstraintLayout and it works. Can you post your XML files?

**Comment by DennisBlock** [comment]
Issue is closed due to inactivity and we were unable to reproduce the bug.
