### ISSUE TITLE
Background problem

### ISSUE THREAD

**Issue by yoloroy** [Team-Blox/TreeView#70]
When I set not solid background - I see this:

![2020-05-13_15-44-12](https://user-images.githubusercontent.com/33396665/81816010-68107080-9533-11ea-8d00-f7a0a9401a4f.png)
![2020-05-13_16-01-09](https://user-images.githubusercontent.com/33396665/81816019-69419d80-9533-11ea-92be-ca7f9b1a7010.png)

`
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    tools:context=".solvers.faces.Resh15Fragment">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginStart="8dp"
        android:layout_marginLeft="8dp"
        android:layout_marginTop="4dp"
        android:layout_marginEnd="8dp"
        android:layout_marginRight="8dp"
        android:layout_marginBottom="8dp"
        android:background="@drawable/rect_corners_s"
        android:backgroundTint="#fff"
        android:elevation="2dp"
        android:gravity="top|end"
        android:orientation="vertical"
        android:paddingStart="12dp"
        android:paddingTop="16dp"
        android:paddingEnd="8dp"
        android:paddingBottom="12dp">

        <Spinner
            android:id="@+id/lang_controller"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="top|end" />

        <de.blox.graphview.GraphView
            android:id="@+id/graphView"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_marginTop="8dp"
            android:layout_weight="1"
            android:background="@drawable/rect_corners_s_stroke">

        </de.blox.graphview.GraphView>
    </LinearLayout>

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/add"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        android:layout_margin="16dp"
        android:clickable="false"
        android:src="@drawable/ic_add"
        android:tint="#fff"
        app:backgroundTint="@color/colorPrimary"
        app:fabSize="normal"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent" />

</FrameLayout>
`

P.S. Thank you for your previous answer

**Comment by DennisBlock** [comment]
Can you explain your problem a little bit more in detail? I don't unterstand whats wrong here.

**Comment by yoloroy** [comment]
somehow background of graphview viewing on nodes, expected this: (added framelayout around)
![2020-05-13_16-30-19](https://user-images.githubusercontent.com/33396665/81818727-11a53100-9537-11ea-919e-0f3d086a7c88.png)

**Comment by GregorBlock** [comment]
It looks like the same problem as last time. Currently padding/margin is not supported.

**Comment by GregorBlock** [comment]
close this issue see #63
