### ISSUE TITLE
Inflating heavy nodes

### ISSUE THREAD

**Issue by duadhruv** [Team-Blox/TreeView#71]
I am trying to draw hierarchy using treeview and the nodes contain photo of the user. Due to this the tree view takes time to inflate the graph and the UI freezes for that time. I tried implementing AsynLayoutInflater in the adapter but that did not work.
Can you provide any way to optimize the inflation?

**Comment by GregorBlock** [comment]
How many nodes does your graph have? Did you consider Glide for loading the images?

**Comment by duadhruv** [comment]
Thanks for the suggestion , it works perfectly now bdw great work!
