### ISSUE TITLE
Cannot resolve symbol 'adapter'

### ISSUE THREAD

**Issue by AnirudhJ3** [Team-Blox/TreeView#72]
I copied the code given in Readme to get started but I got the error at 'adapter = new GraphAdapter<GraphView.ViewHolder>(graph) {' line saying "Cannot resolve symbol 'adapter'". I tried resolving it but implementing suggested resolution of declaring it as type GraphAdapter. After doing this I'm getting error at line 'adapter.setLayout(.....)' since setLayout class is not there in GraphAdapter class but in GraphView class. Please help

**Comment by DennisBlock** [comment]
You're right. There are some errors in the ReadMe. 

You can look at the sample project  how it is done correctly. But what you did is correct. Declaring `adapter` as `GraphAdapter` and using `graphView.setLayout()` instead of `adapter.setLayout()` should work.

**Comment by AnirudhJ3** [comment]
Thanks for the quick response. Also how to add node to the layout dynamically from a button click?

**Comment by DennisBlock** [comment]
Checkout the sample [here](https://github.com/Team-Blox/GraphView/blob/caa318a741a0b9b132658ed818fb7648f124bb7b/sample/src/main/java/de/blox/graphview/sample/GraphActivity.java#L86).

**Comment by AnirudhJ3** [comment]
Got it. Thanks!
