### ISSUE TITLE
Multiple parents

### ISSUE THREAD

**Issue by ProgFroz** [Team-Blox/TreeView#9]
I would like to be able to display multiple parents, such as a 1 - 2 - 1 structure.

**Comment by DennisBlock** [comment]
Hi, this feature will not be implemented in the near future. We want to be able to draw graphs first.

**Comment by herald25santos** [comment]
I can't wait to see this features.

**Comment by lenguyenthanh** [comment]
Hey do you have any idea how to this kind of structure? Like which algorimth or some papers? Please post it here, I may help implement. I need to display this structure too.

**Comment by DennisBlock** [comment]
This is not a tree anymore but a graph. For this kind of layout with multiple parents you need a layerd graph drawing algorithm. There are tons of papers and implementations out there.  E.g. graphiz/dot uses this kind of layout.

**Comment by lenguyenthanh** [comment]
is it a Directed Acyclic Graph?

**Comment by GregorBlock** [comment]
Yes, Layered Graph Drawing aka "Sugiyama Method" work with directed acyclic graphs, possible cycles must be removed.

Edit:
I took a closer look at the algorithm. Cycles are temporarily removed during the layout process and, of course, restored at the end.

**Comment by mpirescarvalho** [comment]
Hey @lenguyenthanh, Did you find a solution to your problem? I need to display this structure too!

**Comment by lenguyenthanh** [comment]
No, we somehow changed to tree structure, so no need to work on this any more.

**Comment by mpirescarvalho** [comment]
Ok, thanks

**Comment by GregorBlock** [comment]
this feature is in now in active development

**Comment by Kenji94** [comment]
Snif I spent so much time doing an algo which dupplicates the nodes.
For example, 
'Wood' extends 'House' & 'Wood' extends 'Wall' 
->
'Wood' extends 'House' & 'Wood[1]' extends 'Wall'

**Comment by GregorBlock** [comment]
You can now use the SugiyamaAlgorithm. It's not perfect yet but it does its job.
